<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tex</string>
	</array>
	<key>firstLineMatch</key>
	<string>^\\starttext</string>
	<key>foldingStartMarker</key>
	<string>\\start.*</string>
	<key>foldingStopMarker</key>
	<string>\\stop.*</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>ConTeXt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.tex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.tex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[^\\](%.*)|(^%.*)</string>
			<key>name</key>
			<string>comment.line.percentage.tex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\\it\s+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.it.context</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>stolen from LaTeX</string>
			<key>contentName</key>
			<string>markup.italic.context</string>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.it.context</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\\bf\s+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.bf.context</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>We put the keyword in a capture and name this capture, so that disabling spell checking for “keyword” won't be inherited by the argument to {\bf...}.

Put specific matches for particular ConTeXt keyword.functions before the last two more general functions</string>
			<key>contentName</key>
			<string>markup.bold.context</string>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.bf.context</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\\bi\s+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.bi.context</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>We put the keyword in a capture and name this capture, so that disabling spell checking for “keyword” won't be inherited by the argument to {\bi...}.

Put specific matches for particular ConTeXt keyword.functions before the last two more general functions</string>
			<key>contentName</key>
			<string>markup.bolditalic.context</string>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.bi.context</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.section.context</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.context</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\(?:part|title|chapter|(?:sub)*(?:section|subject)))\s*(\{.*?\})</string>
			<key>name</key>
			<string>meta.function.section.context</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\start(unique|reusable)?MP)(code|inclusions|graphic)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.document.context</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\stop\2MP)(\3)</string>
			<key>name</key>
			<string>meta.scope.tex.metafun</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.metafun</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.document.context</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\\starttext</string>
			<key>name</key>
			<string>meta.context.starttext</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.document.context</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\\stoptext</string>
			<key>name</key>
			<string>meta.context.stoptext</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.context.group.arguments</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\start)([a-zA-Z]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.enviromnent.context</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.enviromnent.variable</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\stop)(\2)</string>
			<key>name</key>
			<string>meta.context.environment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\\[A-Za-z]+)(?![a-zA-Z])</string>
			<key>name</key>
			<string>support.function.general.tex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.context</string>
	<key>uuid</key>
	<string>20C0FC86-C2D0-4270-8CB9-9D170D703777</string>
</dict>
</plist>
