<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>MetaFun</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>%.*$</string>
			<key>name</key>
			<string>comment.line.percentage.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|upto|endfor)\b</string>
			<key>name</key>
			<string>keyword.control.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)]</string>
			<key>name</key>
			<string>keyword.operator.parentheses.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\[\]\{\}]</string>
			<key>name</key>
			<string>keyword.operator.braces.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(and|or|not)\b)</string>
			<key>name</key>
			<string>keyword.operator.logical.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(sqrt|abs|round|floor|ceiling|sind|cosd|&amp;|\*\*|\*|/|\+-\+|\+\+|\+|-)\b)|(&amp;|\*\*|\*|/|\+-\+|\+\+|\+|-)</string>
			<key>name</key>
			<string>keyword.operator.numeric.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(known|unknown|dotprod|redpart|greenpart|bluepart|substring|null|of|show|to|defaultfont|intersectionpoint)\b)</string>
			<key>name</key>
			<string>keyword.operator.other.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(redpart|greenpart|bluepart)\b)</string>
			<key>name</key>
			<string>keyword.operator.color.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(unitvector|angle|xpart|ypart|subpath)\b)</string>
			<key>name</key>
			<string>keyword.operator.pair.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(scaled|transformed|shifted|(l|u)(l|r)corner|bbox)\b)</string>
			<key>name</key>
			<string>keyword.operator.picture.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(numeric|decimal|boolean|color|transform|path|pair|string|pen|picture|newinternal)\b)</string>
			<key>name</key>
			<string>keyword.operator.declaration.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z_])(white|black|red|green|blue)\b</string>
			<key>name</key>
			<string>constant.language.color.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cycle|pencircle|scaled|dir|tension|curl|label|dotlabel|thelabel|lft|rt|top|bot|ulft|urt|llft|lrt|withcolor)\b</string>
			<key>name</key>
			<string>keyword.other.drawing.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(draw|pickup|show|(un)?fill|buildcycle)\b</string>
			<key>name</key>
			<string>entity.name.function.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(truecorners|bboxmargin|prologues|defaultscale|defaultfont|labeloffset|tracingonline|warningcheck|currentpicture|(full|half)circle|background|whatever)\b</string>
			<key>name</key>
			<string>variable.language.metapost</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(btex|verbatimtex)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tex.metapost</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(etex)</string>
			<key>name</key>
			<string>meta.scope.tex.metapost</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.tex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(def)\s+(\w+\()([^)]*)(\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.definition.metapost</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.metapost</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>declaration.parameter.metapost</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.metapost</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(enddef);</string>
			<key>name</key>
			<string>declaration.function.metapost</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(beginfig\()(\d*)(\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.be.metapost</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.metapost</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.be.metapost</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(endfig)</string>
			<key>name</key>
			<string>meta.environment.fig.metapost</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z_])(-|\+)?\s*[0-9]+(\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z_])(cm|mm|in|pt|bp)\b</string>
			<key>name</key>
			<string>keyword.other.unit.metapost</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--|\.\.)</string>
			<key>name</key>
			<string>meta.connector.metapost</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.metapost</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escaped.metapost</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.metafun</string>
	<key>uuid</key>
	<string>37F68F11-9B52-45EB-A846-AA03D8E6E3C8</string>
</dict>
</plist>
